#third party dependencies folder
set(THIRD_PARTY_DEPS_DIR "${CMAKE_BINARY_DIR}/_third_party_deps")

#own libraries versions
set(PLAYGROUND_VERSION breakout)

#external libraries versions
set(CATCH2_VERSION v3.5.3)