name: Build and Test

on:
  push:
    branches: [ main, master]
  pull_request:
    branches: [ main, master, breakout]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: building and testing
      run: |
        #-DCMAKE_POLICY_VERSION_MINIMUM=3.5 to workaround xiph ogg / vorbis cmake version issues in github workflows
        cmake_options="-DCMAKE_POLICY_VERSION_MINIMUM=3.5" ./cmakew -t .